FROM node:18.16.1-bookworm-slim as build-stage

WORKDIR /usr/src/app/frontend

COPY frontend/package*.json ./

RUN npm ci && npm cache clean --force

RUN npm install -g @angular/cli

COPY frontend/ .

RUN npm run build

FROM nginx

COPY --from=build-stage /usr/src/app/frontend/dist/frontend/ /usr/share/nginx/html

COPY ./nginx/congf.d/default.conf /etc/nginx/conf.d/default.conf
