FROM node:16.18.0-slim as build-stage

WORKDIR /usr/src/app/frontend

COPY frontend/package*.json ./

RUN npm ci && npm cache clean --force

COPY frontend/ .

RUN npm run build

FROM nginx

COPY --from=build-stage /usr/src/app/frontend/dist/frontend/ /usr/share/nginx/html

COPY ./nginx/congf.d/default.conf /etc/nginx/conf.d/default.conf
