services:
  node:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: kinojunkie-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=kinojunkie
    volumes:
      - ./mongodb/seed.js:/docker-entrypoint-initdb.d/seed.js
