networks:
  kinojunkie:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: kinojunkie-nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - php
    networks:
      - kinojunkie

  mysql:
    image: mysql:8
    container_name: kinojunkie-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: kinojunkie
      MYSQL_USER: kinojunkie
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      SERVICE_TAGS: dev
      SERVICE_NAME: kinojunkie-service
    networks:
      - kinojunkie

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kinojunkie-php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - kinojunkie

  composer:
    image: composer:latest
    container_name: kinojunkie-composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - kinojunkie

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kinojunkie-artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - kinojunkie

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: kinojunkie-phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8089:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: test
    networks:
      - kinojunkie
