FROM node:18.16.1-bookworm-slim as development

RUN apt-get update && apt-get install -y procps

WORKDIR /usr/src/app/backend

COPY backend/package*.json ./

RUN npm install

COPY backend/ .

# CMD [ "npm", "run", "start:dev" ]