FROM node:18.16.1-bookworm-slim as build-stage

WORKDIR /usr/src/app/frontend

COPY frontend/package*.json ./

RUN npm ci && npm cache clean --force

COPY frontend/ .

ARG configuration=production

RUN npm run build -- --output-path=/usr/src/app/frontend/dist/out --configuration $configuration

FROM nginx

COPY --from=build-stage /app/dist/out/ /usr/share/nginx/html

COPY ./nginx/congf.d/default.conf /etc/nginx/conf.d/default.conf
